# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
env:
    global:
    - PYTHON=conda
addons:
  apt:
    packages:
    - hdf5-tools
notifications:
  email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("RSDSGE")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
